Render octomaps in ros 3djs
RobotWebTools/ros3djs pull request #312
Opened 2020-04-20 08:48 UTC by psaripp

Add support for subscribing and visualize [`octomap_msgs`](https://github.com/OctoMap/octomap_msgs) messages. Based on [Octomap](https://github.com/OctoMap/octomap) implementation.
- Pretty much similar customization options to *occupancy grid*
- Supports tree in binary form (where only the tree structure is stored), 
- Supports occupancy map with false colouring
- Support octrees with custom colours
- Toggle between rendering modes (if available)
- Select which voxels are visible (free, occupied, all)

2020-04-20 09:30 UTC, psaripp commented
[Example](https://github.com/psaripp/octomap_server) node to publish octomap messages from file.

2020-04-20 10:01 UTC, mvollrath requested changes

2020-04-20 10:01 UTC, mvollrath commented on package-lock.json
> +{
Please do not commit this file in this PR.

2020-04-20 10:01 UTC, mvollrath commented on examples/octree.html
> +    <tt>ros-groovy-rail-maps</tt>
I understand the ROS distro mentioned here is kind of arbitrary, and the other examples probably use the same, but groovy has been EOL since 2014.  How about either:

* Change to melodic or
* Use something like `<distro>` to demonstrate that it you should insert the codename of your distro.

2020-04-20 14:24 UTC, psaripp commented on package-lock.json
> +{
I had removed  this.

2020-04-20 14:26 UTC, psaripp commented on examples/octree.html
> +    <tt>ros-groovy-rail-maps</tt>
I had updated this pointing to my repo. If this sample gets into ros in some way, I'll probably update this as well.

2020-04-22 13:48 UTC, mvollrath approved these changes
Thank you :+1:

2020-04-22 13:50 UTC, merged